### ISSUE TITLE
空指针异常

### ISSUE THREAD

**Issue by 1183226514** [maning0303/MNImageBrowser#18]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
    at com.maning.imagebrowserlibrary.MNImageBrowserActivity.initData(MNImageBrowserActivity.java:145)
    at com.baidu.protect.A.V(Native Method)
    at com.maning.imagebrowserlibrary.MNImageBrowserActivity.onCreate(MNImageBrowserActivity.java:87)

**Comment by maning0303** [comment]
@1183226514 这个我后面做一下集合判断，这个怎么出现的？集合没有数据吗 ？

**Comment by 1183226514** [comment]
> 
> 
> @1183226514 这个我后面做一下集合判断，这个怎么出现的？集合没有数据吗 ？
传过去的集合不会为空，线上出现的，还不知道是在哪种操作情况下出现的

**Comment by maning0303** [comment]
@1183226514 我这边再排查一下相关问题。感谢反馈。

**Comment by maning0303** [comment]
@1183226514 新版本发布，优化了一些问题，你可以先更新看看。初步估计你那个问题应该是界面被销毁数据异常。
